export {
  CAT_CALCULATION_VERSION,
  assignCatToSlot,
  calculateCatRoleEffect,
  calculateRoleScore,
  compareCatForSlot,
  createEmptyCatRoster,
  getAssignableCats,
  getCatForSlot,
  getRoleForSlot,
  isCatAssignable,
  validateCatRoster,
  type CatAssignment,
  type CatAssignmentFailureReason,
  type CatAssignmentResult,
  type CatAttributes,
  type CatAvailabilityState,
  type CatBenefitMetric,
  type CatComparison,
  type CatInstance,
  type CatRarityTier,
  type CatRole,
  type CatRoleEffect,
  type CatRosterState,
  type CatSlotKey,
} from './catDomain';
export {
  createCatProductionModifiers,
  EMPTY_CAT_PRODUCTION_MODIFIERS,
  getMiningOutputMultiplier,
  getHaulingMultiplier,
  type CatProductionModifiers,
} from './catProductionModifiers';
